range1 = range(5, 22, 4)
list1 = list(range1)
print('First list: ', list1)
for i in list1:
    print(i)
range2 = range(26, 4, -7)
list2 = list(range2)
print('Second list: ', list2)
sum2 = sum(list2)
print('Total of the elements in second list: ', sum2)
